version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: bif-fx-dynamodb-local
    ports:
      - '8000:8000'
    command: '-jar DynamoDBLocal.jar -sharedDb -inMemory'
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

volumes:
  dynamodb_data:
